### ISSUE TITLE
Throttle EM requests to max/sec or max parallel?

### ISSUE THREAD

**Issue by chuckyz** [criteo/consul-templaterb#60]
With Consul 1.6.3 limits and a large catalog I had to increase `http_max_conns_per_client` very high (2000) in order to avoid hitting many connection closed errors.

I would be willing to make a small trade-off for max # of RPCs in order to have my templates render slightly slower.

I am not extremely familiar with EventMachine, but perhaps making the threadpool_size configurable can help here?

**Comment by pierresouchay** [comment]
Hello @chuckyz ,

Using very high settings for `limits.http_max_conns_per_client` is not itself a big issue (prior to 1.6.2, this limit did not exist), we plan ourself to use bigger values (32k) when we will have completed our migration to Consul 1.7.x

There are several issues there, first, it is very hard to detect this limit (see https://github.com/hashicorp/consul/issues/7527) for insights, and the linked patch should improve the situation.

Your request is perfectly valid, but it might be very hard to achieve:
 * there are no thread in EventMachine, everything happens in the same thread (see the article [Template-based discovery with consul-templaterb](https://medium.com/criteo-labs/template-based-discovery-with-consul-templaterb-8ff88434c457) or or [here](https://github.com/criteo/consul-templaterb/blob/master/docs/article-06_Template-based_discovery_with_consul-templaterb.md) to read a full description on how it works), so limiting the number of ports is hard to achieve
 * there is a reason why we don't want to limit the number of opened connections: in normal behavior, consul-templaterb using the polling mechanism continuously to watch the changes and have a kind of snapshot view in real-time about all objects required by your templates. Some of these watches might block during 1s, some other for 10 minutes, it is not possible to guess prior to retrieving the answer from Consul itself.

Thus, just opening let's say 100 ports to get a few results would be doable, but performance would be awful: it would require to perform 20x100 connections without waiting and continuously re-do this. Consul cluster would suffer much more (because it would perform tons of RPC queries continuously - in this case something like 20 times more pour a stable cluster)

It would be possible however to change a bit the behavior when using the `--once` flag on command line, but it would be tricky (especially if data is updated during the run), but probably doable, but I am not sure it deserves the complexity.

The real fix would be to implement HTTP2 support in consul-templaterb - which would require a single multiplexed TCP Connection, but unfortunately, it is not supported for now by https://github.com/igrigorik/em-http-request.

**Comment by pierresouchay** [comment]
@chuckyz Hello, do you have comments on this or other ideas, was my answer clear?

**Comment by pierresouchay** [comment]
@chuckyz Closing since no news, feel free to re-open if you still have questions
