### ISSUE TITLE
Expose list of templates objects being generated

### ISSUE THREAD

**Issue by kamaradclimber** [criteo/consul-templaterb#72]
Goal is to be able to have one template rendering after all other templates have been rendered once.
This would serve as a sort of checkpoint "initialization is complete" and would be used as healthcheck for the whole consul-templaterb process.

For instance:

`consul-templaterb -t one_template -t second_template -t health` would be launched and health template would contain something like:

```
<% return nil unless templates.reject { |t| t == __FILE__ }.all?(&:rendered_once) %>
```

This would be a mixup between current api allowing to access *current* template info and the list of other templates.

**Comment by pierresouchay** [comment]
Currently
https://github.com/criteo/consul-templaterb/blob/master/TemplateAPI.md#templates does not expose if template is ready and already rendered.

That's because the object handling the template is not yet create when data is filled up. This is probably possible to add such support by creating a object storing those states (ready/no ready) and being updated when the template callback call is called after first generation of a template.

A possible implementation could be done like something like this in `bin/consul-templaterb`:
```ruby
templates_readyness = {
  by_names = {}
}

...
# Change all references to consul_engine.add_template(source, dest, params) into
consul_engine.add_template(source, dest, params, templates_readyness)
...

# Register the callback to update templates_readyness
consul_engine.add_template_callback do |all_ready, template_manager, results|
  templates_readyness.by_names = results.map {|r| [r.template_file, r.ready]}.to_h
end
```

and provide templates_readyness info into templates() function.

Will be glad to do such kind of review (or alternative one)

**Comment by pierresouchay** [comment]
@kamaradclimber can we close this? (I don't have the rights to, but I think a patch has been provided).
Regards

**Comment by kamaradclimber** [comment]
Indeed, thanks
